### ISSUE TITLE
funannotate2 predict: issues with alignments

### ISSUE THREAD

**Issue by nextgenusfs** [nextgenusfs/funannotate2#1]
Noted that protein and/or transcript alignments generating errors:

Also seems that soft masked stats are not correct....

```
$ funannotate2 predict -f genome.fasta -o output -p output/train_results/genome.params.json -s "Awesome species" -m gfftk --proteins uniprot_sprot.fasta -c 16 

[Nov 03 08:42 PM] Python v3.7.8; funannotate2 v23.11.2; gfftk v23.9.6; buscolite v0.5.1
[Nov 03 08:42 PM] Loaded training params for : ['augustus', 'glimmerhmm', 'snap']
[Nov 03 08:42 PM] temporary files located in: /tmp/predict_18aff407-00c1-45d3-b257-c7edbc134ee6
[Nov 03 08:42 PM] Loading genome assembly, running QC checks, calculating softmasked regions and assembly gaps
[Nov 03 08:42 PM] Genome stats:
{
  "n_contigs": 7,
  "size": 33073878,
  "softmasked": "0.00%",
  "gaps": "0.00%",
  "n50": 4647106,
  "n90": 3621123,
  "l50": 3,
  "l90": 7,
  "avg_length": 4724840
}
[Nov 03 08:42 PM] Aligning protein evidence to the genome assembly with miniprot
[Nov 03 08:59 PM] Generated 109925 alignments: 1282 were valid gene models
[Nov 03 08:59 PM] Parsing alignments and generating hintsfile for augustus
Traceback (most recent call last):
  File "/envs/bin/funannotate2", line 8, in <module>
    sys.exit(main())
  File "/envs//lib/python3.7/site-packages/funannotate2/__main__.py", line 22, in main
    predict(args)
  File "/envs//lib/python3.7/site-packages/funannotate2/predict.py", line 137, in predict
    evidence2hints(ProtAlign, TranAlign, contigs, tmp_dir)
  File "/envs/lib/python3.7/site-packages/funannotate2/abinitio.py", line 1634, in evidence2hints
    p = subprocess.Popen([JOINHINTS], stdin=subprocess.PIPE, stdout=outfile)
  File "/envs//atools/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/envs/lib/python3.7/subprocess.py", line 1465, in _execute_child
    executable = os.fsencode(executable)
  File "//envs/lib/python3.7/os.py", line 812, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
This is probably due to the TranAlign being False in the `evidence2hints` function.

When adding `--transcripts` also getting this error....which seems to be an error in `gapmm2`.
```
[Nov 03 09:19 PM] Python v3.7.8; funannotate2 v23.11.2; gfftk v23.9.6; buscolite v0.5.1
[Nov 03 09:19 PM] Loaded training params for: ['augustus', 'glimmerhmm', 'snap']
[Nov 03 09:19 PM] temporary files located in: /tmp/predict_72772d5a-64b1-423c-ac25-10d955d95cd6
[Nov 03 09:19 PM] Loading genome assembly, running QC checks, calculating softmasked regions and assembly gaps
[Nov 03 09:19 PM] Genome stats:
{
  "n_contigs": 7,
  "size": 33073878,
  "softmasked": "0.00%",
  "gaps": "0.00%",
  "n50": 4647106,
  "n90": 3621123,
  "l50": 3,
  "l90": 7,
  "avg_length": 4724840
}
[Nov 03 09:19 PM] Aligning transcript evidence to the genome assembly with gapmm2
Traceback (most recent call last):
  File "/envs/bin/funannotate2", line 8, in <module>
    sys.exit(main())
  File "/envs/lib/python3.7/site-packages/funannotate2/__main__.py", line 22, in main
    predict(args)
  File "/envs/lib/python3.7/site-packages/funannotate2/predict.py", line 106, in predict
    log=logger,
  File "/envs/lib/python3.7/site-packages/funannotate2/align.py", line 51, in align_transcripts
    fasta, transcripts, threads=cpus, max_intron=max_intron
  File "/envs/lib/python3.7/site-packages/gapmm2/align.py", line 443, in splice_aligner
    paf = right_minus_best_align(paf, ref_idx, h.ctg, h.r_st, seq, h.q_en, offset=6, maxlen=max_intron)
  File "/envs/lib/python3.7/site-packages/gapmm2/align.py", line 391, in right_minus_best_align
    paf = right_update_paf_minus(paf, a, s, refstart-maxlen)
  File "/envs/lib/python3.7/site-packages/gapmm2/align.py", line 254, in right_update_paf_minus
    assert intron_len > 0, "Introns cannot be less than zero"
AssertionError: Introns cannot be less than zero
```

**Comment by nextgenusfs** [comment]
fixed gapmm2 issues upstream and fixed soft masked stats.
